export enum NaturezaOperacao {

  TRIBUTACAO_NO_MUNICIPIO = 'TRIBUTACAO_NO_MUNICIPIO',
  TRIBUTACAO_FORA_DO_MUNICIPIO = 'TRIBUTACAO_FORA_DO_MUNICIPIO',
  ISENCAO = 'ISENCAO',
  IMUNE = 'IMUNE',
  EXIGIBILIDADE_SUSPENSA_POR_DECISAO_JUDICIAL = 'EXIGIBILIDADE_SUSPENSA_POR_DECISAO_JUDICIAL',
  EXIGIBILIDADE_SUSPENSA_POR_PROCEDIMENTO_ADMINISTRATIVO = 'EXIGIBILIDADE_SUSPENSA_POR_PROCEDIMENTO_ADMINISTRATIVO',
}
