export enum OrigemProduto {

  NACIONAL_0 		= 'NACIONAL_0',
  ESTRANGEIRA_1 	= 'ESTRANGEIRA_1',
  ESTRANGEIRA_2 	= 'ESTRANGEIRA_2',
  NACIONAL_3 		= 'NACIONAL_3',
  NACIONAL_4 		= 'NACIONAL_4',
  NACIONAL_5 		= 'NACIONAL_5',
  ESTRANGEIRA_6 	= 'ESTRANGEIRA_6',
  ESTRANGEIRA_7 	= 'ESTRANGEIRA_7',
  NACIONAL_8   	= 'NACIONAL_8'
}
